// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmVkTPCJPD1NEYrJ_bsuC73FwayHFbQME',
    appId: '1:357625708902:web:a82188ea8be81d2a18c8a7',
    messagingSenderId: '357625708902',
    projectId: 'crossdevice-codelab',
    authDomain: 'crossdevice-codelab.firebaseapp.com',
    storageBucket: 'crossdevice-codelab.appspot.com',
    databaseURL: "https://crossdevice-codelab-default-rtdb.firebaseio.com"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_tQAmpd2TRiNvEfrP3BCaDlmHUuVnEnU',
    appId: '1:357625708902:android:33aa96398c3abce818c8a7',
    messagingSenderId: '357625708902',
    projectId: 'crossdevice-codelab',
    storageBucket: 'crossdevice-codelab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_nPJtO5VJ7uJPRKyFEvcS0ryIVDSrxCc',
    appId: '1:357625708902:ios:6b8ffdacf81742fe18c8a7',
    messagingSenderId: '357625708902',
    projectId: 'crossdevice-codelab',
    storageBucket: 'crossdevice-codelab.appspot.com',
    iosClientId: '357625708902-6ifhsb9cc6fcg7on4r3ni5c8kv82fpm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.crossDeviceRemoteController',
  );
}
